name: dodo
description: Dodo
environment:
  sdk: 1.0.0+3.r30188
dependencies:
  analyzer: 0.10.2
  args: 0.9.0
  browser: 0.9.0
  persistent: 0.8.0
  polymer: 0.9.1+1
  sqljocky: 0.9.0
transformers:
- polymer:
    entry_points: web/html/dodo.html
